/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiWorkoutRouteImport } from './routes/api/ai-workout'
import { Route as ApiAiNutritionRouteImport } from './routes/api/ai-nutrition'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiWorkoutRoute = ApiAiWorkoutRouteImport.update({
  id: '/api/ai-workout',
  path: '/api/ai-workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiNutritionRoute = ApiAiNutritionRouteImport.update({
  id: '/api/ai-nutrition',
  path: '/api/ai-nutrition',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/ai-nutrition': typeof ApiAiNutritionRoute
  '/api/ai-workout': typeof ApiAiWorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/ai-nutrition': typeof ApiAiNutritionRoute
  '/api/ai-workout': typeof ApiAiWorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/ai-nutrition': typeof ApiAiNutritionRoute
  '/api/ai-workout': typeof ApiAiWorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/api/ai-nutrition' | '/api/ai-workout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/api/ai-nutrition' | '/api/ai-workout'
  id: '__root__' | '/' | '/app' | '/api/ai-nutrition' | '/api/ai-workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ApiAiNutritionRoute: typeof ApiAiNutritionRoute
  ApiAiWorkoutRoute: typeof ApiAiWorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-workout': {
      id: '/api/ai-workout'
      path: '/api/ai-workout'
      fullPath: '/api/ai-workout'
      preLoaderRoute: typeof ApiAiWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-nutrition': {
      id: '/api/ai-nutrition'
      path: '/api/ai-nutrition'
      fullPath: '/api/ai-nutrition'
      preLoaderRoute: typeof ApiAiNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ApiAiNutritionRoute: ApiAiNutritionRoute,
  ApiAiWorkoutRoute: ApiAiWorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
